name = "newsnow-project"  # 你的项目名称
type = "javascript"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow_db"  # 替换为你创建的数据库名称
database_id = "362225e8-0421-481e-a4f2-5447026adee1"      # 替换为你创建的数据库 ID
